**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [3]:
import numpy as np

array_num = np.random.randint(1,101, 50) 

media = np.mean(array_num)
mediana = np.median(array_num)
desvioPadrao = np.std(array_num)
valorMax = np.max(array_num)
valorMin = np.min(array_num)

print(f"Array Original: {array_num}")
print(f"Média: {media} | Mediana: {mediana} | Desvio Padrão: {desvioPadrao} | Valor Máximo: {valorMax} | Valor Minimo: {valorMin}")

Array Original: [ 98  99  54  79  56  37  55 100  36  10  16  39  15  39  16   5  29  78
  68  27  26  65  17   3  25  10  95  65  80  69   7  30  91  97  79  91
  93  37  21  78  48  88  88  80  20  76  95  85  27  13]
Média: 53.1 | Mediana: 54.5 | Desvio Padrão: 31.668438546919234 | Valor Máximo: 100 | Valor Minimo: 3


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [44]:
array_1 = np.random.randint(1,11, 9).reshape(3, 3)
array_2 = np.random.randint(1,11, 9).reshape(3, 3)

print("array 1: \n", array_1)
print("array 2: \n", array_2)

soma = array_1 + array_2
subtracao = array_1 - array_2
multiplicacao = array_1 * array_2
divisao = array_1 / array_2

print(f"\n\n soma:\n {soma}  | \n\n subtracao: \n {subtracao} | \n\n multiplicacao: \n{multiplicacao}| \n\n divisao:\n {divisao}")

array 1: 
 [[7 6 5]
 [9 5 7]
 [6 8 2]]
array 2: 
 [[ 9  1  5]
 [ 4  1 10]
 [ 1  9  7]]


 soma:
 [[16  7 10]
 [13  6 17]
 [ 7 17  9]]  | 

 subtracao: 
 [[-2  5  0]
 [ 5  4 -3]
 [ 5 -1 -5]] | 

 multiplicacao: 
[[63  6 25]
 [36  5 70]
 [ 6 72 14]]| 

 divisao:
 [[0.77777778 6.         1.        ]
 [2.25       5.         0.7       ]
 [6.         0.88888889 0.28571429]]


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [54]:
array3 = np.random.randint(1,21, (4,4))

somaLinha = np.sum(array3, axis=1)
somaColuna = np.sum(array3, axis=0)

print("array original \n\n", array3)

print(f"\nSoma Linha: {somaLinha}")
print(f"Soma Coluna: {somaColuna}")


array original 

 [[19  9  6 13]
 [ 7 18 11 17]
 [ 7  7  3 13]
 [12 12  2 13]]

Soma Linha: [47 53 30 39]
Soma Coluna: [45 46 22 56]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [9]:
array4 = np.random.randint(0 , 51, 30)
print(f"array original: {array4}")
print(f"Maiores que 25: {array4[array4>25]}")

array original: [ 8 17 15  5 35 49 48 35 32 44 26 25 37 40 42 32 15 19 18  3  1 15 46 42
 14 50 21 31 22 34]
Maiores que 25: [35 49 48 35 32 44 26 37 40 42 32 46 42 50 31 34]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [6]:
arr = np.random.randint(1, 11,(3,3))
print(f"matriz:\n {arr}")
print(f"soma cumulativa: {arr.cumsum()}")
print(f"soma: {arr.sum()}")

matriz:
 [[5 8 7]
 [8 1 1]
 [9 9 9]]
soma cumulativa: [ 5 13 20 28 29 30 39 48 57]
soma: 57
