**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [33]:
import numpy as np

array_num = np.random.randint(1,101, 50) 

media = np.mean(array_num)
mediana = np.median(array_num)
desvioPadrao = np.std(array_num)
valorMax = np.max(array_num)
valorMin = np.min(array_num)

print(f"Array Original: {array_num}")
print(f"Média: {media} | Mediana: {mediana} | Desvio Padrão: {desvioPadrao} | Valor Máximo: {valorMax} | Valor Minimo: {valorMin}")

Array Original: [ 58  38  28  92  80  12  62  33  97 100  30  71  76  28  86  71  16  12
  28  58 100  73  94  56   6  65  31  95  41   7  80  87  34  22  13  13
  50  31  78  85  97  34  64  91  93  10  67  84  85  54]
Média: 56.32 | Mediana: 60.0 | Desvio Padrão: 30.06755061523968 | Valor Máximo: 100 | Valor Minimo: 6


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [44]:
array_1 = np.random.randint(1,11, 9).reshape(3, 3)
array_2 = np.random.randint(1,11, 9).reshape(3, 3)

print("array 1: \n", array_1)
print("array 2: \n", array_2)

soma = array_1 + array_2
subtracao = array_1 - array_2
multiplicacao = array_1 * array_2
divisao = array_1 / array_2

print(f"\n\n soma:\n {soma}  | \n\n subtracao: \n {subtracao} | \n\n multiplicacao: \n{multiplicacao}| \n\n divisao:\n {divisao}")

array 1: 
 [[7 6 5]
 [9 5 7]
 [6 8 2]]
array 2: 
 [[ 9  1  5]
 [ 4  1 10]
 [ 1  9  7]]


 soma:
 [[16  7 10]
 [13  6 17]
 [ 7 17  9]]  | 

 subtracao: 
 [[-2  5  0]
 [ 5  4 -3]
 [ 5 -1 -5]] | 

 multiplicacao: 
[[63  6 25]
 [36  5 70]
 [ 6 72 14]]| 

 divisao:
 [[0.77777778 6.         1.        ]
 [2.25       5.         0.7       ]
 [6.         0.88888889 0.28571429]]


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [54]:
array3 = np.random.randint(1,21, (4,4))

somaLinha = np.sum(array3, axis=1)
somaColuna = np.sum(array3, axis=0)

print("array original \n\n", array3)

print(f"\nSoma Linha: {somaLinha}")
print(f"Soma Coluna: {somaColuna}")


array original 

 [[19  9  6 13]
 [ 7 18 11 17]
 [ 7  7  3 13]
 [12 12  2 13]]

Soma Linha: [47 53 30 39]
Soma Coluna: [45 46 22 56]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [55]:
array4 = np.random.randint(0 , 50, 30)



array([17, 20, 19, 10, 45, 27, 32, 49, 11, 39, 31, 35,  2, 27, 14, 26,  0,
        3, 15, 17, 25, 17, 10, 11, 29, 43, 37, 38,  8, 34])

**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.